name: CI pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Set build variables
        id: vars
        run: |
          echo "DOCKER_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TAG: ${{ steps.vars.outputs.DOCKER_TAG }}
        run: make ci

      - name: Build Summary
        run: |
          echo "### Build Summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "- Image: ${{ secrets.DOCKER_USERNAME }}/popofinder:${{ steps.vars.outputs.DOCKER_TAG }}" >> $GITHUB_STEP_SUMMARY
          echo "- Latest Tag: ${{ secrets.DOCKER_USERNAME }}/popofinder:latest" >> $GITHUB_STEP_SUMMARY
